src/Entity/Article.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Vich\UploaderBundle\Entity\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @Vich\Uploadable()
 * @ORM\Entity
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @ApiResource(
 *     collectionOperations={
 *          "get"={
 *              "normalization_context"={
 *                  "groups"={"read:collection:article"}
 *              }
 *          },
 *          "post"={
 *              "denormalization_context"={
 *                  "groups"={"post:collection:article"}
 *              }
 *          }
 *     },
 *     itemOperations={
            "delete",
 *          "put" = {
 *              "denormalization_context"={
 *                  "groups"={"post:collection:article"}
 *              }
 *          },
 *          "get" = {
                "normalization_context"={
 *                  "groups"={"read:collection:article"}
 *              }
 *          }
 *     }
 * )
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"read:collection:article","post:collection:article"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"read:collection:article","post:collection:article","read:collection:category"})
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Groups({"read:collection:article","post:collection:article","read:collection:category"})
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"read:collection:article","post:collection:article"})
     */
    private $url;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     * @Groups({"read:collection:article","post:collection:article"})
     */
    private $img;

    /**
     * @var File | null
     * @Vich\UploadableField(mapping="articles_img",fileNameProperty="img")
     */
    private $file;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"read:collection:article","post:collection:article","read:collection:category"})
     */
    private $created_at;


    /**
     * @ORM\Column(type="text")
     * @Groups({"read:collection:article","post:collection:article","read:collection:category"})
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     *@Groups({"read:collection:article","post:collection:article","read:collection:category"})
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, mappedBy="articles")
     * @Groups({"read:collection:article","post:collection:article"})
     */
    private $categories;

    /*
     * @Groups({"read:collection:article"})
    */
    private $link;


    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->link = "/article/".$this->id;
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }


    public function getImg(): ?string
    {
        return $this->img;
    }
    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addArticle($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeArticle($this);
        }

        return $this;
    }

    /**
     * @param mixed $file
     */
    public function setFile($file): void
    {
        $this->file = $file;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }


}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('url')
            ->add('file',FileType::class,[
                'required' => false
            ])
            ->add('content')
            ->add('categories',EntityType::class,[
                'class' => Category::class,
                'choice_label' => 'nom',
                'multiple' => true

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article,ArticleRepository $repo): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
            'articles' => $repo->findBy(array(),array(
                'id' => 'DESC'
            ),9),
            'articlesThree' => $repo->findBy(array(),array(
                'id' => 'DESC'
            ),3)
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"POST"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }
        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class=""><i class="fa fa-trash hover:text-red-500"></i></button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    <div class="grid grid-rows-1 my-3">
        <label for="">Title</label>
        {{ form_widget(form.title,{'attr':{'class':'w-full border boder-4 border-black py-1 px-3'}}) }}
    </div>
    <div class="grid grid-rows-1">
        <label for="">Description</label>
        {{ form_widget(form.description,{'attr':{'class':'w-full border boder-4 border-black py-1 px-3'}}) }}
    </div>
    <div class="grid grid-rows-1 my-3">
        <label for="">URL</label>
        {{ form_widget(form.url,{'attr':{'class':'w-full border boder-4 border-black py-1 px-3'}}) }}
    </div>
    <div class="grid grid-rows-1">
        <label for="">Image</label>
        {{ form_widget(form.file,{'attr':{'class':'w-full border boder-4 border-black py-1 px-3'}}) }}
    </div>
    <div class="grid grid-rows-1 my-3">
        <label for="">Content</label>
        {{ form_widget(form.content,{'attr':{'class':'w-full border boder-4 border-black py-1 px-3'}}) }}
    </div>
    <div class="grid grid-rows-1 my-3">
        <label for="">Categories</label>
        {{ form_widget(form.categories,{'attr':{'class':'w-full border boder-4 border-black py-1 px-3'}}) }}
    </div>
    <button class="text-white bg-purple-800 w-full py-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'adminbase.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <div class="w-11/12 mx-auto">
        <h1 class="text-2xl">Article Managed with Symfony</h1>
        <p class="text-right text-green-800 text-xl cursor-pointer"><a href="{{ path('article_new') }}"><i class="fas fa-plus "></i> add post</a></p>

        <table class="w-full">
            <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for article in articles %}
                <tr class="text-center">
                    <td>{{ article.id }}</td>
                    <td class="text-left">{{ article.title }}</td>
                    <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>

                    <td>
                        <div class="flex justify-center ">
                            <a href="{{ path('article_show', {'id': article.id}) }}"><i class="fa fa-eye hover:text-yellow-300"></i></a>
                            <a class="mx-2 md:mx-5" href="{{ path('article_edit', {'id': article.id}) }}"><i class="fas fa-pencil-alt hover:text-green-500"></i></a>
                            {{ include('article/_delete_form.html.twig') }}
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <div class="w-9/12 mx-auto">
        <div class="w-full rounded-md mx-auto p-3 bg-white mt-2">
            <h3 class="text-2xl font-bold">Create an article</h3>
            {{ include('article/_form.html.twig') }}
        </div>
    </div>
    <a href="{{ path('article_index') }}">back to list</a>
{% endblock %}